name: 'Check version in README is latest'
description: 'Checks if the version included in the example in the README is the latest'
branding:
  icon: 'check-circle'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - run: ./action.pl
      shell: bash
