on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Variable check
      run: echo ${GITHUB_ACTION_REPOSITORY}
    - name: Test perl
      run: prove -v
    - id: foo
      uses: ./
