name: Local test
on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Variable check
      run: echo ${GITHUB_REPOSITORY}
    - name: Test perl
      run: prove -v
    - id: foo
      uses: ./
