on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Test perl
      run: prove
    - id: foo
      uses: ./
